services:
  # dag-server:
  #   container_name: dag-server
  #   build:
  #     context: .
  #     dockerfile: server.Dockerfile
  #   ports:
  #     - 8000:8000
  #   environment:
  # dag-worker:
  #   build:
  #     context: .
  #     dockerfile: worker.Dockerfile
  #   deploy:
  #     mode: replicated
  #     replicas: 2
  #   restart: always
  #   environment:
  cache:
      image: redis
      restart: always
      ports:
        - 6379:6379
      command: redis-server --save 60 1 --loglevel warning 
  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin