[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
tokio = { version = "1.33.0", features = ["full"] }
serde_json = "1.0"
thepipelinetool = { git = "https://github.com/thepipelinetool/thepipelinetool.git" }
sqlx = { version = "0.7", default-features = false, features = [ "runtime-tokio", "postgres", "json" ] }

[[bin]]
name = "server"
path = "bin/server.rs"

[[bin]]
name = "worker"
path = "bin/worker.rs"