name: build

on:
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/build.yml
      - server/**
      - server.Dockerfile
      - worker.Dockerfile
      - Cargo.toml
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: server.Dockerfile
          push: true
          platforms: linux/amd64 #, linux/arm64
          tags: ghcr.io/thepipelinetool/server:latest
          cache-from: type=registry,ref=ghcr.io/thepipelinetool/server:buildcache
          cache-to: type=registry,ref=ghcr.io/thepipelinetool/server:buildcache,mode=max
  worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: worker.Dockerfile
          push: true
          platforms: linux/amd64 #, linux/arm64
          tags: ghcr.io/thepipelinetool/worker:latest
          cache-from: type=registry,ref=ghcr.io/thepipelinetool/worker:buildcache
          cache-to: type=registry,ref=ghcr.io/thepipelinetool/worker:buildcache,mode=max